---
steps:
  - name: golang
    args:
      - go
      - mod
      - vendor
    env:
      - 'GO111MODULE=on'
    id: go-mod-vendor
  - name: golang
    entrypoint: bash
    args:
      - -c
      - |
        touch .gcloudignore
        echo '.git' >> .gcloudignore
        echo 'go.*' >> .gcloudignore
    id: 'gcloudignore'
  - name: golang
    entrypoint: cat
    args:
      - '.gcloudignore'
    id: print-gcloudignore
  - name: iankoulski/tree
    entrypoint: tree
    args:
      - './'
    id: tree-dir
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud beta functions deploy backup-firestore \
          --runtime go111 --stage-bucket ${PROJECT_ID}-gcf \
          --trigger-topic backup-firestore --entry-point BackupFirestore \
          --source ./ --region us-central1
    id: deploy-bakcup-firestore
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud beta functions deploy notify-slack \
          --runtime go111 --stage-bucket ${PROJECT_ID}-gcf \
          --trigger-topic cloud-builds --entry-point NotifySlack \
          --source ./ --region asia-northeast1 \
          --set-env-vars SLACK_WEBHOOK=https://slack.com/xxx
    id: deploy-notify-slack
