---
secrets:
  - kmsKeyName: projects/nomos-sms/locations/global/keyRings/nomos-keyring/cryptoKeys/nomos-key
    secretEnv:
      SLACK_WEBHOOK: CiQA1feqkJe8+OcgLAEztRPn2dxIMCiPCJ0V73GSTaLBiZPlwUQSVQCnpGdgtuSk2PEo/XdnHCJJxhh60pw6uKL70GZg9Ldcw2E17HcqOepE4KX0cnwNMU09m3VQhmX1WmQJV7WQRnwYw11recyf6RebfL3WWVVMWPtERPs=

steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud beta functions deploy notify-slack \
          --runtime go111 --stage-bucket nomos-gcf \
          --trigger-topic cloud-builds --entry-point NotifySlack \
          --source ./ --region asia-northeast1 \
          --set-env-vars SLACK_WEBHOOK=$$SLACK_WEBHOOK
    id: deploy-notify-slack
    secretEnv: ['SLACK_WEBHOOK']
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud beta functions deploy backup-firestore \
          --runtime go111 --stage-bucket nomos-gcf \
          --trigger-topic backup-firestore --entry-point BackupFirestore \
          --source ./ --region us-central1
    id: deploy-bakcup-firestore
    waitFor: ['-']
